import { SiThreedotjs, SiTypescript, SiTailwindcss } from "react-icons/si";
import { FaReact, FaJs, FaUnity, FaHtml5, FaCss3Alt } from "react-icons/fa";

export const techStack = [
	{
		id: "React",
		label: "React",
		icon: <FaReact size={32} style={{ fill: "#61DAFB" }} />,
		isIconOnly: true,
		initialX: 16,
		initialY: 16,
		link: "https://reactjs.org/",
	},
	{
		id: "ThreeJS",
		label: "Three.js",
		icon: <SiThreedotjs size={32} style={{ fill: "#FFFFFF" }} />,
		isIconOnly: true,
		initialX: 96,
		initialY: 16,
		link: "https://threejs.org/",
	},
	{
		id: "JavaScript",
		label: "JavaScript",
		icon: <FaJs size={32} style={{ fill: "#F7DF1E" }} />,
		isIconOnly: true,
		initialX: 176,
		initialY: 16,
		link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
	},
	{
		id: "TypeScript",
		label: "TypeScript",
		icon: <SiTypescript size={32} style={{ fill: "#3178C6" }} />,
		isIconOnly: true,
		initialX: 256,
		initialY: 16,
		link: "https://www.typescriptlang.org/",
	},
	{
		id: "Unity",
		label: "Unity",
		icon: <FaUnity size={32} style={{ fill: "#000000" }} />,
		isIconOnly: true,
		initialX: 336,
		initialY: 16,
		link: "https://unity.com/",
	},
	{
		id: "HTML5",
		label: "HTML5",
		icon: <FaHtml5 size={32} style={{ fill: "#E34F26" }} />,
		isIconOnly: true,
		initialX: 416,
		initialY: 16,
		link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
	},
	{
		id: "CSS3",
		label: "CSS3",
		icon: <FaCss3Alt size={32} style={{ fill: "#1572B6" }} />,
		isIconOnly: true,
		initialX: 496,
		initialY: 16,
		link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
	},
	{
		id: "TailwindCSS",
		label: "Tailwind CSS",
		icon: <SiTailwindcss size={32} style={{ fill: "#38B2AC" }} />,
		isIconOnly: true,
		initialX: 16,
		initialY: 96,
		link: "https://tailwindcss.com/",
	},
];